# Generated by Django 3.0.3 on 2020-02-19 09:39
#该文件由命令：python manage.py makemigrations生成，但前提是需要在model.py中写好要建立的表
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='签名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateField()),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotweb.Account')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='robotweb.Tag')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
    ]
