# Generated by Django 3.0.3 on 2020-03-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robotweb', '0002_auto_20200301_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(max_length=64)),
                ('accountname', models.CharField(max_length=128)),
                ('parentaccount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=64)),
                ('companyname', models.CharField(max_length=64)),
                ('Parentcompany', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittdate', models.DateTimeField(auto_now_add=True)),
                ('accountdate', models.DateField()),
                ('versionname', models.CharField(max_length=64, unique=True)),
                ('actualorbudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotweb.AccountType')),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotweb.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('userid', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotweb.Company')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotweb.Account')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotweb.Version')),
            ],
        ),
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotweb.Account')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotweb.Version')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accounttypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotweb.AccountType'),
        ),
    ]
